### ISSUE TITLE
Emit adds event to pending list prior to checking handler for its existence

### ISSUE THREAD

**Issue by eventsourcer** [MessageHandler/MessageHandler.Feedback#1]
This could result in duplicate events stored in the absence of the corresponding Apply method since no logic to apply is present.
Ensuring a handler exists before adding to pending is necessary in my opinion.

<img width="643" alt="Capture" src="https://github.com/user-attachments/assets/edf3c036-8fc8-4573-9e31-9abdaf30dcae">

**Comment by yvesgoeleven** [comment]
Understandable, it used to be this way in an older version. But sometimes the aggregate doesn't need any info from previous events for deciding on future commands, having to implement an empty handler at the point is also not ideal. Hence I removed the handler check.

**Comment by eventsourcer** [comment]
this was the only reason that I could think of. running event's logic against the aggregate is made optional.
thanks for explaining
